import { Inter } from "next/font/google";
import "./globals.css";
import { StateProvider } from "./providers/StateProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" style={{ height: "100%" }}>
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.2.19/tailwind.min.css" integrity="sha512-YEvSlJ7lFL7Ss/5dWeIzGxpujO0CwFGoDYkDwOdmJKrhz/3Ig/yC8j87n6CbO3YCe45OCesPvOUJvJ5I/rgRg==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
        <style>{inter.styles}</style>
      </head>
      <body className="bg-blue-100">
        <StateProvider>
          {children}
        </StateProvider>
      </body>
    </html>
  );
}
